AimPoint30/AimPoint30/Models/ErrorViewModel.cs
namespace AimPoint30.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AimPoint30/AimPoint30/Controllers/CalculosController.cs
using Microsoft.AspNetCore.Mvc;

namespace AimPoint30.Controllers
{
    public class CalculosController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public CalculosController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {


            return View();
        }
    }
}

AimPoint30/AimPoint30/Controllers/ColetasController.cs
using Microsoft.AspNetCore.Mvc;

namespace AimPoint30.Controllers
{
    public class ColetasController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ColetasController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {


            return View();
        }
    }
}

AimPoint30/AimPoint30/Controllers/DashboarController.cs
using AimPoint30.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using AimPoint30.Entities.ViewModels;
using AimPoint30.Domain.Logics;
namespace AimPoint30.Controllers
{
    public class DashboardController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public DashboardController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var business = new DashboardBusiness();
            DashboardViewModel home = business.ObterDashboardValores();

            ViewBag.Message = home;

            return View();
        }
       
    }
}

AimPoint30/AimPoint30/Controllers/HomeController.cs
using AimPoint30.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using AimPoint30.Entities.ViewModels;
using AimPoint30.Domain.Logics;


namespace AimPoint30.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AimPoint30/AimPoint30/Views/Calculos/Index.cshtml
@{
    ViewData["Title"] = "Cálculos";
}
@{
    ViewBag.Title = "Cálculos";
    
}

<div class="container text-center" style="background-color:rgba(255,255,255,0.6);margin-top:37px;border-radius:20px">
        
       <h1 class="display-4 fw-bold" style="padding:30px;color:black;">Cálculos</h1>
        
</div>

AimPoint30/AimPoint30/Views/Coletas/Index.cshtml
@{
    ViewData["Title"] = "Coletas";
}
@{
    ViewBag.Title = "Coletas";
    
}
<div class="container text-center" style="background-color:rgba(255,255,255,0.6);margin-top:37px;border-radius:20px">
        
       <h1 class="display-4 fw-bold" style="padding:30px;color:black;">Coletas</h1>
        
</div>

AimPoint30/AimPoint30/Views/Dashboard/Index.cshtml
@using AimPoint30.Entities.Model
@using AimPoint30.Entities.ViewModels
@using AimPoint30.Controllers;


@model DashboardViewModel
@{
    ViewData["Title"] = "Dashboard";
    var data = ViewBag.Message;
    ViewBag.Title = "Dashboard";
}


<div class="container text-center" style="height:1500px;background-color:rgba(255,255,255,0.6);margin-top:37px;border-radius:20px">
        
    <h1 class="display-4 fw-bold" style="padding:30px;color:black;">Dashboard</h1>

    <div class="container">
        <div class="row"style="padding-top:20px">
             <div class="container bg-white" style="width:450px;height:350px;border-radius:20px;">
                 <h2 class="fw-bold" style="padding-top:20px;color:rgba(90,70,0,1)"> Base 6 minutos <img src="/icons/kisspng-investment-money-real-estate-investing-clip-art-eis-clipart-5b49ef0b5e7064.4423728315315719793868.png" style="height:10%;width:10%"/></h2>
                 <ul class="list-group" style="margin-top:25px">
                     <il class="list-group-item h4">Data da coleta:</il>
                     <il class="list-group-item h4">Valor coletado:</il>
                     <il class="list-group-item h4">Data alvo:</il>
                 </ul>
                 <h3 style="margin-top:20px">Valor previsto</h3>
                 <h3></h3>
            </div>

            <div class="container bg-white" style="width:450px;height:350px;border-radius:20px;box-shadow:3px">
                 <h2 class="fw-bold" style="padding-top:20px;color:rgba(90,70,0,1)"> Base 30 minutos <img src="/icons/kisspng-investment-money-real-estate-investing-clip-art-eis-clipart-5b49ef0b5e7064.4423728315315719793868.png" style="height:10%;width:10%"/></h2>
                 <ul class="list-group" style="margin-top:25px">
                     <il class="list-group-item h4">Data da coleta:</il>
                     <il class="list-group-item h4">Valor coletado:</il>
                     <il class="list-group-item h4">Data alvo:</il>
                 </ul>
                 <h3 style="margin-top:20px">Valor previsto</h3>
            </div>
        </div>
               
         <div class="row" style="padding-top:80px">
             <div class="container bg-white" style="width:450px;height:350px;border-radius:20px;">
                  <h2 class="fw-bold" style="padding-top:20px;color:rgba(90,70,0,1)"> Base 3 horas <img src="/icons/kisspng-investment-money-real-estate-investing-clip-art-eis-clipart-5b49ef0b5e7064.4423728315315719793868.png" style="height:10%;width:10%"/></h2>
                  <ul class="list-group" style="margin-top:25px">
                     <il class="list-group-item h4">Data da coleta:</il>
                     <il class="list-group-item h4">Valor coletado:</il>
                     <il class="list-group-item h4">Data alvo:</il>
                 </ul>
                 <h3 style="padding-top:20px">Valor previsto</h3>
            </div>

            <div class="container bg-white" style="width:450px;height:350px;border-radius:20px;box-shadow:3px">
                 <h2 class="fw-bold" style="padding-top:20px;color:rgba(90,70,0,1)"> Base 1 dia <img src="/icons/kisspng-investment-money-real-estate-investing-clip-art-eis-clipart-5b49ef0b5e7064.4423728315315719793868.png" style="height:10%;width:10%"/></h2>
                 <ul class="list-group" style="margin-top:25px;color:rgba(0,0,0,1)">
                     <il class="list-group-item h4">Data da coleta: @data.Vday1.DateInit</il>
                     <il class="list-group-item h4">Valor coletado: US$ @data.Vday1.PriceInit</il>
                     <il class="list-group-item h4">Data alvo:</il>
                 </ul>
                 <h3 style="padding-top:20px">Valor previsto</h3>
            </div>
        </div> 
        
        <div class="row" style="padding-top:80px">
             <div class="container bg-white" style="width:450px;height:350px;border-radius:20px;">
                  <h2 class="fw-bold" style="padding-top:20px;color:rgba(90,70,0,1)"> Base 1 semana <img src="/icons/kisspng-investment-money-real-estate-investing-clip-art-eis-clipart-5b49ef0b5e7064.4423728315315719793868.png" style="height:10%;width:10%"/></h2>
                  <ul class="list-group" style="margin-top:25px">
                     <il class="list-group-item h4">Data da coleta:</il>
                     <il class="list-group-item h4">Valor coletado:</il>
                     <il class="list-group-item h4">Data alvo:</il>
                 </ul>
                 <h3 style="padding-top:20px">Valor previsto</h3>
            </div>

            <div class="container bg-white" style="width:450px;height:350px;border-radius:20px;box-shadow:3px">
                 
                 <h2 class="fw-bold" style="padding-top:20px;color:rgba(90,70,0,1)"> Base 4 semanas <img src="/icons/kisspng-investment-money-real-estate-investing-clip-art-eis-clipart-5b49ef0b5e7064.4423728315315719793868.png" style="height:10%;width:10%"/></h2>
                 
                 <ul class="list-group" style="margin-top:25px">
                     <il class="list-group-item h4">Data da coleta:</il>
                     <il class="list-group-item h4">Valor coletado:</il>
                     <il class="list-group-item h4">Data alvo:</il>
                 </ul>
                 <h3 style="padding-top:20px">Valor previsto</h3>
            </div>
        </div>
      
    </div>
        
    <h1 class="display-4 fw-bold text-danger">  </h1>
        
</div>

AimPoint30/AimPoint30/Views/Home/Index.cshtml
@using AimPoint30.Entities.Model
@using AimPoint30.Entities.ViewModels
@using AimPoint30.Controllers;


@{
    ViewData["Title"] = "Home";
    
    ViewBag.Title = "Home";
}


<div class="container text-center" style="background-color:rgba(255,255,255,0.6);margin-top:37px;border-radius:20px">
        
    <h1 class="display-4 fw-bold" style="padding:30px;color:black;"> Bem Vindo </h1>
    <p class="h3" style="padding-top:20px;color:rgba(90,70,0,1)"> 
        Para acessar as funcionalidades desta aplicação
        basta abrir o menu <mark class="h5" style="background-color:black;color:white"> <i class="fa fa-light fa-table"></i> Resgistros</mark> 
         no cabeçalho, como demonstrado na imagem abaixo.
    </p>
    <img src="/icons/ImageHome1.png" style="padding-bottom:40px;border-radius:10px"/>

    
        
</div>

AimPoint30/AimPoint30/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" asp-append-version="true"  />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AimPoint30.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" asp-append-version="true"  />
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-black">
            <div class="container-fluid">
                <a href="@Url.Action("Index","Home")" style="width:115px;height:55px;"><img class="navbar-brand " src="/icons/Home.png" style="width:100%;height:100%;"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div id="navbarCollapse" class="collapse navbar-collapse" style="padding-left:8px;">
                    <ul class="nav navbar-nav">
                                              
                        <li class="nav-item dropdown fs-6 fw-semibold ">
                            <a href="#" class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown"> <i class="fa fa-light fa-table"></i> Registros </a>
                            <div class="dropdown-menu ">
                                <a href="@Url.Action("Index","Dashboard")" class="dropdown-item fs-7 fw-semibold text-danger"><i class="fa fa-solid fa-gauge"></i> Dashboard </a>
                                <a href="@Url.Action("Index","Coletas")" class="dropdown-item fs-7 fw-semibold text-danger"><i class="fa fa-solid fa-sack-dollar"></i></> Coletas </a>
                                <a href="@Url.Action("Index","Calculos")" class="dropdown-item fs-7 fw-semibold text-danger"><i class="fa fa-solid fa-chart-line"></i> Calculos </a>
                            </div>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container"  >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="navbar fixed-bottom pb-0" style="height:50px;">
        <div class="container fs-6 text-light" style="padding-bottom:20px">
            &copy; 2022 - AimPoint System </a>
        </div> 
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>